/*
 * Game of Thrones television-canon episode catalogue.
 * Plot summaries, themes, and character links are original editorial metadata.
 */

const EPISODE_SOURCE_NOTE =
  "The 73-episode TV canon was checked against HBO/WBD's official series material; titles, season order, credits, air dates, and runtimes were cross-checked against the cited open episode catalogue, individual episode records, and TVMaze. Summaries, themes, and character links are original editorial additions for this project.";

const EPISODE_SOURCES = Object.freeze([
  Object.freeze({
    label: "HBO/WBD Pressroom — The Iron Anniversary",
    url: "https://press.wbd.com/us/ca/media-release/hbo-0/game-thrones-s1/hbo-announces-iron-anniversary-month-long-celebration-commemorate-10th-anniversary",
    covers: Object.freeze(["official 73-episode count", "television canon"])
  }),
  Object.freeze({
    label: "Wikipedia — List of Game of Thrones episodes",
    url: "https://en.wikipedia.org/wiki/List_of_Game_of_Thrones_episodes",
    covers: Object.freeze(["titles", "season order", "directors", "writers", "air dates"])
  }),
  Object.freeze({
    label: "Wikipedia — Game of Thrones episode articles",
    url: "https://en.wikipedia.org/wiki/Category:Game_of_Thrones_episodes",
    covers: Object.freeze(["episode runtimes", "credit cross-checks"])
  }),
  Object.freeze({
    label: "TVMaze — Game of Thrones episode API",
    url: "https://api.tvmaze.com/shows/82/episodes",
    covers: Object.freeze(["air-date cross-checks", "runtime cross-checks"])
  })
]);

const EPISODES = Object.freeze([
  {
    id: "s01e01",
    season: 1,
    episode: 1,
    title: "Winter Is Coming",
    airDate: "2011-04-17",
    runtime: 61,
    director: "Tim Van Patten",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Robert asks Ned to become Hand while Daenerys enters a political marriage and Bran's discovery of the Lannister twins ends in a devastating fall.",
    themes: ["Family", "Power", "Betrayal"],
    characterIds: ["ned-stark", "bran-stark", "jaime-lannister", "jon-snow", "daenerys-targaryen"],
    eventIds: ["ev-s1-hand", "ev-s1-drogo-wed", "ev-s1-bran-fall"]
  },
  {
    id: "s01e02",
    season: 1,
    episode: 2,
    title: "The Kingsroad",
    airDate: "2011-04-24",
    runtime: 55,
    director: "Tim Van Patten",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "As the Stark family scatters along the Kingsroad and toward the Wall, an attack on Bran and Joffrey's cruelty deepen suspicion and loss.",
    themes: ["Family", "Duty", "Justice"],
    characterIds: ["ned-stark", "arya-stark", "sansa-stark", "bran-stark", "jon-snow"]
  },
  {
    id: "s01e03",
    season: 1,
    episode: 3,
    title: "Lord Snow",
    airDate: "2011-05-01",
    runtime: 57,
    director: "Brian Kirk",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Ned confronts the crown's debt, Jon learns humility at the Wall, and a pregnant Daenerys begins resisting Viserys.",
    themes: ["Power", "Identity", "Leadership"],
    characterIds: ["ned-stark", "jon-snow", "tyrion-lannister", "daenerys-targaryen", "bran-stark"]
  },
  {
    id: "s01e04",
    season: 1,
    episode: 4,
    title: "Cripples, Bastards, and Broken Things",
    airDate: "2011-05-08",
    runtime: 55,
    director: "Brian Kirk",
    writers: ["Bryan Cogman"],
    summary: "Ned follows Jon Arryn's trail, Jon protects Sam at the Wall, and Catelyn arrests Tyrion after linking him to Bran's attack.",
    themes: ["Justice", "Loyalty", "Identity"],
    characterIds: ["ned-stark", "catelyn-stark", "tyrion-lannister", "jon-snow", "samwell-tarly"]
  },
  {
    id: "s01e05",
    season: 1,
    episode: 5,
    title: "The Wolf and the Lion",
    airDate: "2011-05-15",
    runtime: 54,
    director: "Brian Kirk",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Ned resigns rather than sanction Daenerys's murder, while Catelyn takes Tyrion to the Eyrie and Jaime retaliates in King's Landing.",
    themes: ["Duty", "Justice", "Revenge"],
    characterIds: ["ned-stark", "catelyn-stark", "tyrion-lannister", "jaime-lannister", "robert-baratheon"]
  },
  {
    id: "s01e06",
    season: 1,
    episode: 6,
    title: "A Golden Crown",
    airDate: "2011-05-22",
    runtime: 52,
    director: "Daniel Minahan",
    writers: ["Jane Espenson", "David Benioff", "D. B. Weiss"],
    summary: "Tyrion wins his freedom by combat, Ned uncovers the royal children's parentage, and Drogo gives Viserys the fatal crown he demanded.",
    themes: ["Justice", "Power", "Death"],
    characterIds: ["tyrion-lannister", "ned-stark", "daenerys-targaryen", "viserys-targaryen", "khal-drogo"]
  },
  {
    id: "s01e07",
    season: 1,
    episode: 7,
    title: "You Win or You Die",
    airDate: "2011-05-29",
    runtime: 57,
    director: "Daniel Minahan",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Robert's death opens a succession struggle, Littlefinger betrays Ned, and Drogo vows to carry Daenerys's cause across the Narrow Sea.",
    themes: ["Power", "Betrayal", "War"],
    characterIds: ["ned-stark", "cersei-lannister", "joffrey-baratheon", "petyr-baelish", "daenerys-targaryen"],
    eventIds: ["ev-s1-robert-death"]
  },
  {
    id: "s01e08",
    season: 1,
    episode: 8,
    title: "The Pointy End",
    airDate: "2011-06-05",
    runtime: 58,
    director: "Daniel Minahan",
    writers: ["George R. R. Martin"],
    summary: "Arya escapes, Sansa becomes Joffrey's hostage, Robb summons the North, and danger from both war and the dead closes around the Starks.",
    themes: ["Family", "War", "Survival"],
    characterIds: ["arya-stark", "sansa-stark", "robb-stark", "jon-snow", "daenerys-targaryen"]
  },
  {
    id: "s01e09",
    season: 1,
    episode: 9,
    title: "Baelor",
    airDate: "2011-06-12",
    runtime: 56,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Robb captures Jaime through a costly feint, Daenerys turns to blood magic, and Joffrey breaks his promise by executing Ned.",
    themes: ["War", "Betrayal", "Death"],
    characterIds: ["ned-stark", "robb-stark", "catelyn-stark", "joffrey-baratheon", "daenerys-targaryen"],
    eventIds: ["ev-s1-ned-death"]
  },
  {
    id: "s01e10",
    season: 1,
    episode: 10,
    title: "Fire and Blood",
    airDate: "2011-06-19",
    runtime: 52,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "The North crowns Robb, Arya and Jon begin new journeys, Tyrion is named Hand, and Daenerys emerges from Drogo's pyre with three dragons.",
    themes: ["Leadership", "Identity", "Prophecy"],
    characterIds: ["robb-stark", "arya-stark", "jon-snow", "tyrion-lannister", "daenerys-targaryen"],
    eventIds: ["ev-s1-drogo-death"]
  },
  {
    id: "s02e01",
    season: 2,
    episode: 1,
    title: "The North Remembers",
    airDate: "2012-04-01",
    runtime: 52,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Five kings press competing claims as Tyrion assumes the Handship, Robb seeks alliances, and Daenerys leads her dwindling people into the Red Waste.",
    themes: ["Power", "War", "Leadership"],
    characterIds: ["tyrion-lannister", "cersei-lannister", "stannis-baratheon", "robb-stark", "daenerys-targaryen"]
  },
  {
    id: "s02e02",
    season: 2,
    episode: 2,
    title: "The Night Lands",
    airDate: "2012-04-08",
    runtime: 53,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Theon returns to a hostile Pyke, Arya trusts Gendry with her identity, and Jon discovers the price Craster pays to the White Walkers.",
    themes: ["Identity", "Family", "Betrayal"],
    characterIds: ["theon-greyjoy", "balon-greyjoy", "yara-greyjoy", "arya-stark", "jon-snow"]
  },
  {
    id: "s02e03",
    season: 2,
    episode: 3,
    title: "What Is Dead May Never Die",
    airDate: "2012-04-15",
    runtime: 52,
    director: "Alik Sakharov",
    writers: ["Bryan Cogman"],
    summary: "Theon chooses his birth family, Tyrion exposes Pycelle's spying, Brienne joins Renly's guard, and Arya's northbound refuge is destroyed.",
    themes: ["Identity", "Loyalty", "Betrayal"],
    characterIds: ["theon-greyjoy", "tyrion-lannister", "arya-stark", "catelyn-stark", "brienne-of-tarth"]
  },
  {
    id: "s02e04",
    season: 2,
    episode: 4,
    title: "Garden of Bones",
    airDate: "2012-04-22",
    runtime: 50,
    director: "David Petrarca",
    writers: ["Vanessa Taylor"],
    summary: "Robb meets Talisa after victory, Joffrey punishes Sansa, Arya enters Tywin's service, and Melisandre brings a deadly shadow into the world.",
    themes: ["War", "Power", "Faith"],
    characterIds: ["robb-stark", "talisa-stark", "joffrey-baratheon", "arya-stark", "melisandre"]
  },
  {
    id: "s02e05",
    season: 2,
    episode: 5,
    title: "The Ghost of Harrenhal",
    airDate: "2012-04-29",
    runtime: 54,
    director: "David Petrarca",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Renly's murder reshapes the war, Brienne swears herself to Catelyn, Arya names her first victim, and Theon turns his ambition toward Winterfell.",
    themes: ["Death", "Loyalty", "Revenge"],
    characterIds: ["renly-baratheon", "catelyn-stark", "brienne-of-tarth", "arya-stark", "theon-greyjoy"],
    eventIds: ["ev-s2-renly-death"]
  },
  {
    id: "s02e06",
    season: 2,
    episode: 6,
    title: "The Old Gods and the New",
    airDate: "2012-05-06",
    runtime: 54,
    director: "David Nutter",
    writers: ["Vanessa Taylor"],
    summary: "Theon captures Winterfell, Jon becomes isolated with Ygritte, a royal riot engulfs King's Landing, and Daenerys's dragons disappear in Qarth.",
    themes: ["Betrayal", "Power", "Survival"],
    characterIds: ["theon-greyjoy", "bran-stark", "jon-snow", "ygritte", "daenerys-targaryen"]
  },
  {
    id: "s02e07",
    season: 2,
    episode: 7,
    title: "A Man Without Honor",
    airDate: "2012-05-13",
    runtime: 55,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Theon hunts the escaped Stark boys, Jaime's failed escape fuels vengeance, Jon is trapped by wildlings, and Daenerys learns who stole her dragons.",
    themes: ["Identity", "Revenge", "Survival"],
    characterIds: ["theon-greyjoy", "jaime-lannister", "jon-snow", "sansa-stark", "daenerys-targaryen"]
  },
  {
    id: "s02e08",
    season: 2,
    episode: 8,
    title: "The Prince of Winterfell",
    airDate: "2012-05-20",
    runtime: 53,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Catelyn secretly frees Jaime to recover her daughters, Stannis closes on the capital, and Tyrion prepares a desperate defense with wildfire.",
    themes: ["Family", "War", "Duty"],
    characterIds: ["catelyn-stark", "jaime-lannister", "brienne-of-tarth", "stannis-baratheon", "tyrion-lannister"]
  },
  {
    id: "s02e09",
    season: 2,
    episode: 9,
    title: "Blackwater",
    airDate: "2012-05-27",
    runtime: 55,
    director: "Neil Marshall",
    writers: ["George R. R. Martin"],
    summary: "Tyrion's wildfire plan breaks Stannis's fleet, but the battle for King's Landing turns only when Tywin and the Tyrells arrive.",
    themes: ["War", "Leadership", "Survival"],
    characterIds: ["tyrion-lannister", "stannis-baratheon", "davos-seaworth", "cersei-lannister", "joffrey-baratheon"],
    eventIds: ["ev-s2-blackwater"]
  },
  {
    id: "s02e10",
    season: 2,
    episode: 10,
    title: "Valar Morghulis",
    airDate: "2012-06-03",
    runtime: 63,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Daenerys reclaims her dragons, Jon kills Qhorin to enter the wildlings' trust, Theon loses Winterfell, and the White Walker army advances.",
    themes: ["Death", "Identity", "Survival"],
    characterIds: ["daenerys-targaryen", "jon-snow", "qhorin-halfhand", "theon-greyjoy", "arya-stark"],
    eventIds: ["ev-s2-robb-talisa"]
  },
  {
    id: "s03e01",
    season: 3,
    episode: 1,
    title: "Valar Dohaeris",
    airDate: "2013-03-31",
    runtime: 54,
    director: "Daniel Minahan",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon meets Mance Rayder, Daenerys considers buying the Unsullied, Tyrion seeks his reward, and Davos returns to challenge Melisandre's influence.",
    themes: ["Leadership", "Power", "Loyalty"],
    characterIds: ["jon-snow", "mance-rayder", "daenerys-targaryen", "tyrion-lannister", "davos-seaworth"]
  },
  {
    id: "s03e02",
    season: 3,
    episode: 2,
    title: "Dark Wings, Dark Words",
    airDate: "2013-04-07",
    runtime: 57,
    director: "Daniel Minahan",
    writers: ["Vanessa Taylor"],
    summary: "Bran meets the Reeds, Arya encounters the Brotherhood, Jaime and Brienne begin their forced journey, and Theon awakens in a new captivity.",
    themes: ["Identity", "Survival", "Prophecy"],
    characterIds: ["bran-stark", "arya-stark", "jaime-lannister", "brienne-of-tarth", "theon-greyjoy"]
  },
  {
    id: "s03e03",
    season: 3,
    episode: 3,
    title: "Walk of Punishment",
    airDate: "2013-04-14",
    runtime: 52,
    director: "David Benioff",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jaime loses his sword hand while Daenerys bargains for the Unsullied, Jon faces the wildlings' demands, and Tyrion is ordered to marry Sansa.",
    themes: ["Power", "Identity", "Justice"],
    characterIds: ["jaime-lannister", "brienne-of-tarth", "daenerys-targaryen", "jon-snow", "tyrion-lannister"]
  },
  {
    id: "s03e04",
    season: 3,
    episode: 4,
    title: "And Now His Watch Is Ended",
    airDate: "2013-04-21",
    runtime: 53,
    director: "Alex Graves",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Daenerys turns her purchase of the Unsullied into Astapor's liberation as mutiny destroys the Night's Watch refuge and Jaime struggles with his mutilation.",
    themes: ["Freedom", "Leadership", "Betrayal"],
    characterIds: ["daenerys-targaryen", "grey-worm", "jaime-lannister", "jeor-mormont", "arya-stark"],
    eventIds: ["ev-s3-unsullied"]
  },
  {
    id: "s03e05",
    season: 3,
    episode: 5,
    title: "Kissed by Fire",
    airDate: "2013-04-28",
    runtime: 57,
    director: "Alex Graves",
    writers: ["Bryan Cogman"],
    summary: "Jaime reveals why he killed the Mad King, Jon and Ygritte become lovers, Robb executes Karstark, and Beric grants the Hound trial by combat.",
    themes: ["Duty", "Love", "Justice"],
    characterIds: ["jaime-lannister", "brienne-of-tarth", "jon-snow", "ygritte", "robb-stark"],
    eventIds: ["ev-s3-jon-ygritte"]
  },
  {
    id: "s03e06",
    season: 3,
    episode: 6,
    title: "The Climb",
    airDate: "2013-05-05",
    runtime: 53,
    director: "Alik Sakharov",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon and Ygritte scale the Wall, Tywin forces dynastic marriages, and Littlefinger explains how chaos rewards those willing to climb.",
    themes: ["Power", "Love", "Betrayal"],
    characterIds: ["jon-snow", "ygritte", "tyrion-lannister", "cersei-lannister", "petyr-baelish"]
  },
  {
    id: "s03e07",
    season: 3,
    episode: 7,
    title: "The Bear and the Maiden Fair",
    airDate: "2013-05-12",
    runtime: 57,
    director: "Michelle MacLaren",
    writers: ["George R. R. Martin"],
    summary: "Jaime returns for Brienne at Harrenhal, Robb seeks Frey support, Jon's loyalties are tested, and Daenerys reaches Yunkai.",
    themes: ["Loyalty", "Duty", "Love"],
    characterIds: ["jaime-lannister", "brienne-of-tarth", "robb-stark", "jon-snow", "daenerys-targaryen"]
  },
  {
    id: "s03e08",
    season: 3,
    episode: 8,
    title: "Second Sons",
    airDate: "2013-05-19",
    runtime: 56,
    director: "Michelle MacLaren",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Tyrion marries Sansa without claiming her, Daenerys gains the Second Sons, and Melisandre proves the power of royal blood to Gendry.",
    themes: ["Duty", "Power", "Faith"],
    characterIds: ["tyrion-lannister", "sansa-stark", "daenerys-targaryen", "gendry-baratheon", "melisandre"]
  },
  {
    id: "s03e09",
    season: 3,
    episode: 9,
    title: "The Rains of Castamere",
    airDate: "2013-06-02",
    runtime: 50,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Walder Frey's hospitality becomes a massacre that ends Robb's rebellion, while Jon escapes the wildlings and Daenerys takes Yunkai.",
    themes: ["Betrayal", "Death", "War"],
    characterIds: ["robb-stark", "catelyn-stark", "arya-stark", "jon-snow", "daenerys-targaryen"],
    eventIds: ["ev-s3-redwedding"]
  },
  {
    id: "s03e10",
    season: 3,
    episode: 10,
    title: "Mhysa",
    airDate: "2013-06-09",
    runtime: 62,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "The realm absorbs the Red Wedding as Arya travels with the Hound, Bran crosses the Wall, Jaime returns home, and freed Yunkish hail Daenerys.",
    themes: ["Freedom", "Family", "Identity"],
    characterIds: ["arya-stark", "sandor-clegane", "bran-stark", "jaime-lannister", "daenerys-targaryen"]
  },
  {
    id: "s04e01",
    season: 4,
    episode: 1,
    title: "Two Swords",
    airDate: "2014-04-06",
    runtime: 58,
    director: "D. B. Weiss",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Tywin reforges Ice, Jaime refuses Cersei's demand, Daenerys marches toward Meereen, and Arya reclaims Needle with the Hound.",
    themes: ["Identity", "Revenge", "Power"],
    characterIds: ["arya-stark", "sandor-clegane", "tyrion-lannister", "jaime-lannister", "daenerys-targaryen"]
  },
  {
    id: "s04e02",
    season: 4,
    episode: 2,
    title: "The Lion and the Rose",
    airDate: "2014-04-13",
    runtime: 52,
    director: "Alex Graves",
    writers: ["George R. R. Martin"],
    summary: "Joffrey dies at his wedding feast, leaving Tyrion accused, Sansa spirited away, and the capital's alliances suddenly uncertain.",
    themes: ["Death", "Power", "Betrayal"],
    characterIds: ["joffrey-baratheon", "tyrion-lannister", "sansa-stark", "cersei-lannister", "margaery-tyrell"],
    eventIds: ["ev-s4-purplewedding"]
  },
  {
    id: "s04e03",
    season: 4,
    episode: 3,
    title: "Breaker of Chains",
    airDate: "2014-04-20",
    runtime: 56,
    director: "Alex Graves",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Sansa escapes with Littlefinger, Tyrion prepares for trial, Sam seeks safety for Gilly, and Daenerys confronts Meereen with its own cruelty.",
    themes: ["Freedom", "Justice", "Survival"],
    characterIds: ["sansa-stark", "petyr-baelish", "tyrion-lannister", "samwell-tarly", "daenerys-targaryen"]
  },
  {
    id: "s04e04",
    season: 4,
    episode: 4,
    title: "Oathkeeper",
    airDate: "2014-04-27",
    runtime: 55,
    director: "Michelle MacLaren",
    writers: ["Bryan Cogman"],
    summary: "Jaime arms Brienne to find Sansa, Daenerys frees Meereen, Jon leads a mission against the mutineers, and Bran reaches Craster's Keep.",
    themes: ["Duty", "Freedom", "Loyalty"],
    characterIds: ["jaime-lannister", "brienne-of-tarth", "daenerys-targaryen", "jon-snow", "bran-stark"]
  },
  {
    id: "s04e05",
    season: 4,
    episode: 5,
    title: "First of His Name",
    airDate: "2014-05-04",
    runtime: 53,
    director: "Michelle MacLaren",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Tommen is crowned, Cersei and Margaery compete for influence, Sansa enters the Eyrie, and Bran chooses his northern destiny over reunion with Jon.",
    themes: ["Power", "Family", "Prophecy"],
    characterIds: ["tommen-baratheon", "cersei-lannister", "margaery-tyrell", "sansa-stark", "bran-stark"]
  },
  {
    id: "s04e06",
    season: 4,
    episode: 6,
    title: "The Laws of Gods and Men",
    airDate: "2014-05-11",
    runtime: 50,
    director: "Alik Sakharov",
    writers: ["Bryan Cogman"],
    summary: "Tyrion's trial becomes a public reckoning with his family, while Davos secures the Iron Bank and Daenerys learns the cost of ruling.",
    themes: ["Justice", "Family", "Leadership"],
    characterIds: ["tyrion-lannister", "jaime-lannister", "tywin-lannister", "davos-seaworth", "daenerys-targaryen"]
  },
  {
    id: "s04e07",
    season: 4,
    episode: 7,
    title: "Mockingbird",
    airDate: "2014-05-18",
    runtime: 51,
    director: "Alik Sakharov",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Tyrion chooses trial by combat, Sansa survives Lysa's fury, the Hound's wounds worsen, and Littlefinger reveals the depth of his manipulation.",
    themes: ["Justice", "Survival", "Betrayal"],
    characterIds: ["tyrion-lannister", "oberyn-martell", "sansa-stark", "petyr-baelish", "arya-stark"]
  },
  {
    id: "s04e08",
    season: 4,
    episode: 8,
    title: "The Mountain and the Viper",
    airDate: "2014-06-01",
    runtime: 52,
    director: "Alex Graves",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Oberyn fights for vengeance against the Mountain but loses both the duel and Tyrion's hope of acquittal.",
    themes: ["Revenge", "Justice", "Death"],
    characterIds: ["oberyn-martell", "gregor-clegane", "tyrion-lannister", "sansa-stark", "petyr-baelish"],
    eventIds: ["ev-s4-mountain-viper"]
  },
  {
    id: "s04e09",
    season: 4,
    episode: 9,
    title: "The Watchers on the Wall",
    airDate: "2014-06-08",
    runtime: 50,
    director: "Neil Marshall",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon and the Night's Watch defend Castle Black through the night, paying for survival with the lives of friends and foes alike.",
    themes: ["War", "Duty", "Death"],
    characterIds: ["jon-snow", "ygritte", "samwell-tarly", "tormund-giantsbane", "alliser-thorne"],
    eventIds: ["ev-s4-wall-attack"]
  },
  {
    id: "s04e10",
    season: 4,
    episode: 10,
    title: "The Children",
    airDate: "2014-06-15",
    runtime: 65,
    director: "Alex Graves",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Tyrion kills Shae and Tywin before fleeing, Arya abandons the Hound for Braavos, Bran reaches the raven, and Daenerys restrains her dragons.",
    themes: ["Family", "Death", "Freedom"],
    characterIds: ["tyrion-lannister", "tywin-lannister", "arya-stark", "sandor-clegane", "bran-stark"],
    eventIds: ["ev-s4-tywin-death"]
  },
  {
    id: "s05e01",
    season: 5,
    episode: 1,
    title: "The Wars to Come",
    airDate: "2015-04-12",
    runtime: 52,
    director: "Michael Slovis",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Cersei remembers a prophecy of loss, Tyrion reaches Pentos, Daenerys faces insurgency in Meereen, and Jon offers Mance a fatal choice.",
    themes: ["Prophecy", "Power", "Justice"],
    characterIds: ["cersei-lannister", "tyrion-lannister", "daenerys-targaryen", "jon-snow", "mance-rayder"]
  },
  {
    id: "s05e02",
    season: 5,
    episode: 2,
    title: "The House of Black and White",
    airDate: "2015-04-19",
    runtime: 55,
    director: "Michael Slovis",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Arya enters the House of Black and White, Jon is elected Lord Commander, and Daenerys's pursuit of justice divides Meereen.",
    themes: ["Identity", "Leadership", "Justice"],
    characterIds: ["arya-stark", "jon-snow", "daenerys-targaryen", "brienne-of-tarth", "cersei-lannister"]
  },
  {
    id: "s05e03",
    season: 5,
    episode: 3,
    title: "High Sparrow",
    airDate: "2015-04-26",
    runtime: 59,
    director: "Mark Mylod",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Cersei watches Margaery gain influence, Jon asserts his command, Arya tries to shed her identity, and Sansa is promised to Ramsay.",
    themes: ["Power", "Identity", "Faith"],
    characterIds: ["cersei-lannister", "margaery-tyrell", "jon-snow", "arya-stark", "sansa-stark"]
  },
  {
    id: "s05e04",
    season: 5,
    episode: 4,
    title: "Sons of the Harpy",
    airDate: "2015-05-03",
    runtime: 50,
    director: "Mark Mylod",
    writers: ["Dave Hill"],
    summary: "The Faith arrests Loras, Jaime and Bronn reach Dorne, Jon seeks a wildling alliance, and the Sons of the Harpy strike Daenerys's council.",
    themes: ["Faith", "War", "Loyalty"],
    characterIds: ["jaime-lannister", "bronn", "jon-snow", "daenerys-targaryen", "barristan-selmy"]
  },
  {
    id: "s05e05",
    season: 5,
    episode: 5,
    title: "Kill the Boy",
    airDate: "2015-05-10",
    runtime: 56,
    director: "Jeremy Podeswa",
    writers: ["Bryan Cogman"],
    summary: "Jon chooses Hardhome despite opposition, Tyrion and Jorah sail toward Meereen, Sansa finds an ally, and Daenerys makes a political marriage.",
    themes: ["Leadership", "Duty", "Power"],
    characterIds: ["jon-snow", "tormund-giantsbane", "daenerys-targaryen", "tyrion-lannister", "sansa-stark"]
  },
  {
    id: "s05e06",
    season: 5,
    episode: 6,
    title: "Unbowed, Unbent, Unbroken",
    airDate: "2015-05-17",
    runtime: 53,
    director: "Jeremy Podeswa",
    writers: ["Bryan Cogman"],
    summary: "Sansa is forced to marry Ramsay, Arya receives her first Faceless assignment, Jaime's rescue fails, and Tyrion and Jorah are sold into combat.",
    themes: ["Power", "Identity", "Survival"],
    characterIds: ["sansa-stark", "ramsay-bolton", "arya-stark", "jaime-lannister", "tyrion-lannister"]
  },
  {
    id: "s05e07",
    season: 5,
    episode: 7,
    title: "The Gift",
    airDate: "2015-05-24",
    runtime: 58,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Cersei's empowered Faith imprisons her, Jon departs for Hardhome, Sansa asks Theon for help, and Tyrion finally stands before Daenerys.",
    themes: ["Faith", "Power", "Survival"],
    characterIds: ["cersei-lannister", "jon-snow", "sansa-stark", "theon-greyjoy", "tyrion-lannister"]
  },
  {
    id: "s05e08",
    season: 5,
    episode: 8,
    title: "Hardhome",
    airDate: "2015-05-31",
    runtime: 60,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon rescues wildlings at Hardhome until the Night King raises the fallen, while Tyrion persuades Daenerys to accept his counsel.",
    themes: ["Survival", "Death", "Leadership"],
    characterIds: ["jon-snow", "tormund-giantsbane", "the-night-king", "tyrion-lannister", "daenerys-targaryen"],
    eventIds: ["ev-s5-hardhome"]
  },
  {
    id: "s05e09",
    season: 5,
    episode: 9,
    title: "The Dance of Dragons",
    airDate: "2015-06-07",
    runtime: 52,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Stannis sacrifices Shireen to escape winter, Daenerys survives the fighting pits on Drogon, and Arya abandons her mission for vengeance.",
    themes: ["Faith", "Death", "Revenge"],
    characterIds: ["stannis-baratheon", "shireen-baratheon", "daenerys-targaryen", "jon-snow", "arya-stark"],
    eventIds: ["ev-s5-shireen"]
  },
  {
    id: "s05e10",
    season: 5,
    episode: 10,
    title: "Mother's Mercy",
    airDate: "2015-06-14",
    runtime: 60,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Cersei endures public humiliation, Stannis's campaign collapses, Daenerys meets a Dothraki horde, Sansa escapes Winterfell, and mutineers stab Jon.",
    themes: ["Justice", "Betrayal", "Survival"],
    characterIds: ["cersei-lannister", "stannis-baratheon", "daenerys-targaryen", "sansa-stark", "jon-snow"],
    eventIds: ["ev-s5-sept-of-baelor", "ev-s5-jon-mutiny"]
  },
  {
    id: "s06e01",
    season: 6,
    episode: 1,
    title: "The Red Woman",
    airDate: "2016-04-24",
    runtime: 50,
    director: "Jeremy Podeswa",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Davos protects Jon's body, Sansa accepts Brienne's service, Cersei mourns Myrcella, and Melisandre's confidence collapses behind a startling revelation.",
    themes: ["Faith", "Loyalty", "Identity"],
    characterIds: ["jon-snow", "davos-seaworth", "melisandre", "sansa-stark", "cersei-lannister"]
  },
  {
    id: "s06e02",
    season: 6,
    episode: 2,
    title: "Home",
    airDate: "2016-05-01",
    runtime: 53,
    director: "Jeremy Podeswa",
    writers: ["Dave Hill"],
    summary: "Melisandre restores Jon to life, Ramsay seizes Bolton power, Bran witnesses young Winterfell, and Euron returns to overthrow Balon.",
    themes: ["Faith", "Power", "Death"],
    characterIds: ["jon-snow", "melisandre", "ramsay-bolton", "bran-stark", "balon-greyjoy"],
    eventIds: ["ev-s6-jon-resurrection"]
  },
  {
    id: "s06e03",
    season: 6,
    episode: 3,
    title: "Oathbreaker",
    airDate: "2016-05-08",
    runtime: 52,
    director: "Daniel Sackheim",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon executes his killers and ends his watch, Bran sees the Tower of Joy, Arya regains her sight, and Daenerys faces the khals.",
    themes: ["Justice", "Identity", "Prophecy"],
    characterIds: ["jon-snow", "bran-stark", "arya-stark", "daenerys-targaryen", "samwell-tarly"]
  },
  {
    id: "s06e04",
    season: 6,
    episode: 4,
    title: "Book of the Stranger",
    airDate: "2016-05-15",
    runtime: 58,
    director: "Daniel Sackheim",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon and Sansa reunite and plan to retake Winterfell, Daenerys commands the Dothraki, and Tyrion's compromise unsettles Meereen.",
    themes: ["Family", "Leadership", "Power"],
    characterIds: ["jon-snow", "sansa-stark", "daenerys-targaryen", "tyrion-lannister", "cersei-lannister"]
  },
  {
    id: "s06e05",
    season: 6,
    episode: 5,
    title: "The Door",
    airDate: "2016-05-22",
    runtime: 56,
    director: "Jack Bender",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Bran's reckless vision lets the Night King breach the cave, forcing Hodor to fulfill the tragic command that shaped his life.",
    themes: ["Duty", "Death", "Prophecy"],
    characterIds: ["bran-stark", "hodor", "meera-reed", "the-night-king", "sansa-stark"]
  },
  {
    id: "s06e06",
    season: 6,
    episode: 6,
    title: "Blood of My Blood",
    airDate: "2016-05-29",
    runtime: 51,
    director: "Jack Bender",
    writers: ["Bryan Cogman"],
    summary: "Benjen rescues Bran and Meera, Daenerys rallies the Dothraki, Sam brings Gilly home, and Jaime prepares to confront the Blackfish.",
    themes: ["Family", "Loyalty", "Leadership"],
    characterIds: ["bran-stark", "benjen-stark", "daenerys-targaryen", "samwell-tarly", "jaime-lannister"]
  },
  {
    id: "s06e07",
    season: 6,
    episode: 7,
    title: "The Broken Man",
    airDate: "2016-06-05",
    runtime: 50,
    director: "Mark Mylod",
    writers: ["Bryan Cogman"],
    summary: "The Hound returns to violence after finding his community slain, while Jon and Sansa recruit the North and Jaime begins the siege of Riverrun.",
    themes: ["Revenge", "War", "Leadership"],
    characterIds: ["sandor-clegane", "jon-snow", "sansa-stark", "jaime-lannister", "arya-stark"]
  },
  {
    id: "s06e08",
    season: 6,
    episode: 8,
    title: "No One",
    airDate: "2016-06-12",
    runtime: 58,
    director: "Mark Mylod",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Arya defeats the Waif and reclaims her name, Jaime takes Riverrun through Edmure, and Daenerys returns as Meereen comes under attack.",
    themes: ["Identity", "Power", "War"],
    characterIds: ["arya-stark", "jaime-lannister", "brienne-of-tarth", "daenerys-targaryen", "sandor-clegane"]
  },
  {
    id: "s06e09",
    season: 6,
    episode: 9,
    title: "Battle of the Bastards",
    airDate: "2016-06-19",
    runtime: 59,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Daenerys crushes the slavers' assault and allies with Yara, while Jon and Sansa defeat Ramsay in the battle for Winterfell.",
    themes: ["War", "Leadership", "Revenge"],
    characterIds: ["jon-snow", "sansa-stark", "ramsay-bolton", "daenerys-targaryen", "theon-greyjoy"],
    eventIds: ["ev-s6-bastards"]
  },
  {
    id: "s06e10",
    season: 6,
    episode: 10,
    title: "The Winds of Winter",
    airDate: "2016-06-26",
    runtime: 68,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Cersei destroys the Sept and takes the crown, Jon becomes King in the North, Bran learns Jon's parentage, and Daenerys sails west.",
    themes: ["Power", "Death", "Prophecy"],
    characterIds: ["cersei-lannister", "jon-snow", "daenerys-targaryen", "bran-stark", "arya-stark"],
    eventIds: ["ev-s6-tower-of-joy", "ev-s6-sept-explosion", "ev-s6-kitn"]
  },
  {
    id: "s07e01",
    season: 7,
    episode: 1,
    title: "Dragonstone",
    airDate: "2017-07-16",
    runtime: 59,
    director: "Jeremy Podeswa",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Arya ends House Frey's male line, Jon organizes the North, Cersei courts Euron, Sam discovers Dragonstone's dragonglass, and Daenerys comes home.",
    themes: ["Revenge", "Leadership", "Power"],
    characterIds: ["arya-stark", "jon-snow", "cersei-lannister", "samwell-tarly", "daenerys-targaryen"]
  },
  {
    id: "s07e02",
    season: 7,
    episode: 2,
    title: "Stormborn",
    airDate: "2017-07-23",
    runtime: 58,
    director: "Mark Mylod",
    writers: ["Bryan Cogman"],
    summary: "Jon accepts Daenerys's summons, Sam risks everything to cure Jorah, Arya turns toward Winterfell, and Euron devastates Yara's fleet.",
    themes: ["Duty", "Family", "War"],
    characterIds: ["daenerys-targaryen", "jon-snow", "arya-stark", "samwell-tarly", "theon-greyjoy"]
  },
  {
    id: "s07e03",
    season: 7,
    episode: 3,
    title: "The Queen's Justice",
    airDate: "2017-07-30",
    runtime: 63,
    director: "Mark Mylod",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon and Daenerys clash over fealty but cooperate on dragonglass, Cersei avenges Myrcella, and Olenna confesses her role in Joffrey's death.",
    themes: ["Justice", "Power", "Revenge"],
    characterIds: ["jon-snow", "daenerys-targaryen", "cersei-lannister", "jaime-lannister", "olenna-tyrell"]
  },
  {
    id: "s07e04",
    season: 7,
    episode: 4,
    title: "The Spoils of War",
    airDate: "2017-08-06",
    runtime: 49,
    director: "Matt Shakman",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Arya returns to Winterfell, Jon shows Daenerys evidence of the dead, and Drogon leads a fiery assault on Jaime's army.",
    themes: ["Family", "War", "Power"],
    characterIds: ["arya-stark", "sansa-stark", "daenerys-targaryen", "jaime-lannister", "bronn"],
    eventIds: ["ev-s7-loot-castamere"]
  },
  {
    id: "s07e05",
    season: 7,
    episode: 5,
    title: "Eastwatch",
    airDate: "2017-08-13",
    runtime: 58,
    director: "Matt Shakman",
    writers: ["Dave Hill"],
    summary: "Daenerys executes the defiant Tarlys, Tyrion arranges an armistice appeal, and Jon assembles a party to capture proof of the dead.",
    themes: ["Justice", "Duty", "War"],
    characterIds: ["daenerys-targaryen", "jon-snow", "tyrion-lannister", "jorah-mormont", "gendry-baratheon"]
  },
  {
    id: "s07e06",
    season: 7,
    episode: 6,
    title: "Beyond the Wall",
    airDate: "2017-08-20",
    runtime: 70,
    director: "Alan Taylor",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon's expedition captures a wight but requires Daenerys's rescue, costing her Viserion and giving the Night King a dragon.",
    themes: ["Duty", "Death", "War"],
    characterIds: ["jon-snow", "daenerys-targaryen", "the-night-king", "arya-stark", "sansa-stark"]
  },
  {
    id: "s07e07",
    season: 7,
    episode: 7,
    title: "The Dragon and the Wolf",
    airDate: "2017-08-27",
    runtime: 79,
    director: "Jeremy Podeswa",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "The living present their proof to Cersei, the Stark siblings condemn Littlefinger, Jon's parentage is confirmed, and the undead breach the Wall.",
    themes: ["Betrayal", "Identity", "War"],
    characterIds: ["jon-snow", "daenerys-targaryen", "cersei-lannister", "jaime-lannister", "bran-stark"],
    eventIds: ["ev-s7-dragonpit", "ev-s7-wall-falls", "ev-s7-jon-dany"]
  },
  {
    id: "s08e01",
    season: 8,
    episode: 1,
    title: "Winterfell",
    airDate: "2019-04-14",
    runtime: 53,
    director: "David Nutter",
    writers: ["Dave Hill"],
    summary: "Jon and Daenerys bring their armies to Winterfell, Sam reveals Jon's true name, Theon rescues Yara, and Jaime faces Bran again.",
    themes: ["Identity", "Family", "Duty"],
    characterIds: ["jon-snow", "daenerys-targaryen", "samwell-tarly", "jaime-lannister", "cersei-lannister"]
  },
  {
    id: "s08e02",
    season: 8,
    episode: 2,
    title: "A Knight of the Seven Kingdoms",
    airDate: "2019-04-21",
    runtime: 57,
    director: "David Nutter",
    writers: ["Bryan Cogman"],
    summary: "Winterfell's defenders settle old debts and share a final night together as Jaime knights Brienne and Jon tells Daenerys his parentage.",
    themes: ["Duty", "Love", "Death"],
    characterIds: ["jaime-lannister", "brienne-of-tarth", "jon-snow", "daenerys-targaryen", "sansa-stark"]
  },
  {
    id: "s08e03",
    season: 8,
    episode: 3,
    title: "The Long Night",
    airDate: "2019-04-28",
    runtime: 81,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Winterfell survives the longest night through terrible sacrifice when Arya reaches the godswood and destroys the Night King.",
    themes: ["War", "Death", "Survival"],
    characterIds: ["arya-stark", "the-night-king", "bran-stark", "theon-greyjoy", "daenerys-targaryen"],
    eventIds: ["ev-s8-winterfell"]
  },
  {
    id: "s08e04",
    season: 8,
    episode: 4,
    title: "The Last of the Starks",
    airDate: "2019-05-05",
    runtime: 77,
    director: "David Nutter",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Victory gives way to rivalry and grief as Jon's secret spreads, Rhaegal is killed, Missandei is executed, and Daenerys turns toward vengeance.",
    themes: ["Power", "Betrayal", "Revenge"],
    characterIds: ["daenerys-targaryen", "jon-snow", "sansa-stark", "jaime-lannister", "missandei"]
  },
  {
    id: "s08e05",
    season: 8,
    episode: 5,
    title: "The Bells",
    airDate: "2019-05-12",
    runtime: 77,
    director: "Miguel Sapochnik",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "King's Landing surrenders, but Daenerys burns the city while Jaime and Cersei die together and Arya escapes the devastation.",
    themes: ["War", "Power", "Death"],
    characterIds: ["daenerys-targaryen", "jon-snow", "tyrion-lannister", "jaime-lannister", "arya-stark"],
    eventIds: ["ev-s8-kingslanding", "ev-s8-cersei-jaime-death"]
  },
  {
    id: "s08e06",
    season: 8,
    episode: 6,
    title: "The Iron Throne",
    airDate: "2019-05-19",
    runtime: 78,
    director: "David Benioff & D. B. Weiss",
    writers: ["David Benioff", "D. B. Weiss"],
    summary: "Jon kills Daenerys to end her conquest, Bran is chosen king, the North becomes independent, and the surviving Starks choose separate futures.",
    themes: ["Power", "Justice", "Freedom"],
    characterIds: ["jon-snow", "daenerys-targaryen", "tyrion-lannister", "bran-stark", "sansa-stark"],
    eventIds: ["ev-s8-dany-death", "ev-s8-bran-king"]
  }
].map((record) => Object.freeze({
  ...record,
  writers: Object.freeze(record.writers),
  themes: Object.freeze(record.themes),
  characterIds: Object.freeze(record.characterIds),
  eventIds: Object.freeze(record.eventIds || [])
})));

if (typeof window !== "undefined") {
  window.EPISODE_SOURCE_NOTE = EPISODE_SOURCE_NOTE;
  window.EPISODE_SOURCES = EPISODE_SOURCES;
  window.EPISODES = EPISODES;
}
