// Shared timeline dataset — feeds the Timeline/Seasons Explorer, character-page
// timelines, and house-page timelines. Season-level granularity, TV canon.
//
// type: "battle" | "death" | "wedding" | "coronation" | "politics" | "birth" | "other"
const events = [
  { id: "ev-s1-hand", season: 1, title: "Ned Stark becomes Hand of the King", date: "Season 1", type: "politics", houses: ["Stark", "Baratheon"], characters: ["ned-stark", "robert-baratheon"], summary: "Eddard Stark reluctantly agrees to become Robert Baratheon's Hand after Jon Arryn's death." },
  { id: "ev-s1-drogo-wed", season: 1, title: "Daenerys weds Khal Drogo", date: "Season 1", type: "wedding", houses: ["Targaryen"], characters: ["daenerys-targaryen", "khal-drogo", "viserys-targaryen"], summary: "Illyrio Mopatis brokers Daenerys's marriage to the Dothraki khal in exchange for an army to reclaim the Iron Throne." },
  { id: "ev-s1-bran-fall", season: 1, title: "Bran Stark is pushed from a tower", date: "Season 1", type: "other", houses: ["Stark", "Lannister"], characters: ["bran-stark", "jaime-lannister"], summary: "Jaime Lannister pushes Bran from a Winterfell tower after he witnesses Jaime and Cersei together." },
  { id: "ev-s1-robert-death", season: 1, title: "Death of Robert Baratheon", date: "Season 1", type: "death", houses: ["Baratheon"], characters: ["robert-baratheon", "cersei-lannister"], summary: "Robert dies from wounds after a boar hunt engineered by Cersei's wine." },
  { id: "ev-s1-ned-death", season: 1, title: "Execution of Ned Stark", date: "Season 1", type: "death", houses: ["Stark", "Lannister"], characters: ["ned-stark", "joffrey-baratheon"], summary: "Joffrey has Ned Stark publicly beheaded on the steps of the Great Sept, igniting the War of the Five Kings." },
  { id: "ev-s1-drogo-death", season: 1, title: "Death of Khal Drogo & birth of the dragons", date: "Season 1", type: "death", houses: ["Targaryen"], characters: ["khal-drogo", "daenerys-targaryen", "mirri-maz-duur"], summary: "Drogo dies after Mirri Maz Duur's blood magic; Daenerys walks into his funeral pyre and emerges with three living dragons." },

  { id: "ev-s2-blackwater", season: 2, title: "Battle of the Blackwater", date: "Season 2", type: "battle", houses: ["Lannister", "Baratheon", "Tyrell"], characters: ["tyrion-lannister", "stannis-baratheon", "cersei-lannister", "davos-seaworth"], summary: "Tyrion's wildfire trap and a timely Tyrell relief force smash Stannis Baratheon's assault on King's Landing." },
  { id: "ev-s2-renly-death", season: 2, title: "Death of Renly Baratheon", date: "Season 2", type: "death", houses: ["Baratheon"], characters: ["renly-baratheon", "melisandre", "stannis-baratheon"], summary: "A shadow creature born of Melisandre and Stannis assassinates Renly on the eve of battle." },
  { id: "ev-s2-robb-talisa", season: 2, title: "Robb Stark marries Talisa", date: "Season 2", type: "wedding", houses: ["Stark"], characters: ["robb-stark", "talisa-stark"], summary: "Robb breaks his betrothal to a Frey daughter to marry Talisa, sowing the seeds of the Red Wedding." },

  { id: "ev-s3-redwedding", season: 3, title: "The Red Wedding", date: "Season 3", type: "death", houses: ["Stark", "Tully"], characters: ["robb-stark", "catelyn-stark", "talisa-stark", "walder-frey", "roose-bolton"], summary: "House Frey and House Bolton butcher Robb Stark, Catelyn Stark, and their bannermen at Edmure and Roslin's wedding feast." },
  { id: "ev-s3-jon-ygritte", season: 3, title: "Jon Snow and Ygritte", date: "Season 3", type: "other", houses: ["Stark", "Free Folk"], characters: ["jon-snow", "ygritte"], summary: "Jon infiltrates the wildlings and falls for the spearwife Ygritte before returning to the Night's Watch." },
  { id: "ev-s3-unsullied", season: 3, title: "Daenerys frees the Unsullied", date: "Season 3", type: "politics", houses: ["Targaryen"], characters: ["daenerys-targaryen", "grey-worm", "missandei"], summary: "Daenerys tricks Kraznys mo Nakloz, burns Astapor's masters, and frees an army of Unsullied soldiers." },

  { id: "ev-s4-purplewedding", season: 4, title: "The Purple Wedding", date: "Season 4", type: "death", houses: ["Lannister", "Tyrell"], characters: ["joffrey-baratheon", "olenna-tyrell", "margaery-tyrell"], summary: "King Joffrey is poisoned at his own wedding feast; Olenna Tyrell is later revealed as the culprit." },
  { id: "ev-s4-mountain-viper", season: 4, title: "Trial by combat: The Mountain vs. The Red Viper", date: "Season 4", type: "battle", houses: ["Lannister", "Martell"], characters: ["gregor-clegane", "oberyn-martell", "tyrion-lannister"], summary: "Oberyn Martell fights to prove Tyrion's innocence but is killed by Gregor Clegane in gruesome fashion." },
  { id: "ev-s4-tywin-death", season: 4, title: "Tyrion kills Tywin Lannister", date: "Season 4", type: "death", houses: ["Lannister"], characters: ["tyrion-lannister", "tywin-lannister", "shae"], summary: "After discovering Shae in his father's bed, Tyrion kills her, then shoots Tywin with a crossbow and flees the city." },
  { id: "ev-s4-wall-attack", season: 4, title: "Wildling assault on Castle Black", date: "Season 4", type: "battle", houses: ["Night's Watch", "Free Folk"], characters: ["jon-snow", "mance-rayder", "ygritte", "grenn", "pyp"], summary: "Mance Rayder's wildling host storms the Wall; Jon Snow rallies the Night's Watch to hold Castle Black." },

  { id: "ev-s5-sept-of-baelor", season: 5, title: "Cersei's Walk of Atonement", date: "Season 5", type: "other", houses: ["Lannister"], characters: ["cersei-lannister", "septa-unella"], summary: "The Faith Militant forces Cersei to walk naked through King's Landing as public penance." },
  { id: "ev-s5-hardhome", season: 5, title: "Battle of Hardhome", date: "Season 5", type: "battle", houses: ["Night's Watch", "Free Folk"], characters: ["jon-snow", "the-night-king", "tormund-giantsbane", "karsi"], summary: "The Night King's army of the dead overruns the wildling refuge at Hardhome as Jon Snow watches in horror." },
  { id: "ev-s5-shireen", season: 5, title: "Sacrifice of Shireen Baratheon", date: "Season 5", type: "death", houses: ["Baratheon"], characters: ["shireen-baratheon", "stannis-baratheon", "melisandre", "selyse-baratheon"], summary: "Stannis allows Melisandre to burn his daughter Shireen alive to secure a victory, dooming his campaign." },
  { id: "ev-s5-jon-mutiny", season: 5, title: "Mutiny at Castle Black", date: "Season 5", type: "death", houses: ["Night's Watch"], characters: ["jon-snow", "alliser-thorne", "olly"], summary: "Alliser Thorne and other Night's Watch officers stab Jon Snow to death for bringing wildlings beyond the Wall." },

  { id: "ev-s6-jon-resurrection", season: 6, title: "Jon Snow is resurrected", date: "Season 6", type: "other", houses: ["Stark", "Night's Watch"], characters: ["jon-snow", "melisandre", "davos-seaworth"], summary: "Melisandre uses the Lord of Light's magic to bring Jon Snow back from death." },
  { id: "ev-s6-tower-of-joy", season: 6, title: "Tower of Joy flashback confirms R+L=J", date: "Season 6", type: "other", houses: ["Stark", "Targaryen"], characters: ["ned-stark", "lyanna-stark", "rhaegar-targaryen", "jon-snow"], summary: "Bran witnesses the truth: Jon Snow is the son of Lyanna Stark and Rhaegar Targaryen, not Ned's bastard." },
  { id: "ev-s6-bastards", season: 6, title: "Battle of the Bastards", date: "Season 6", type: "battle", houses: ["Stark", "Bolton"], characters: ["jon-snow", "ramsay-bolton", "sansa-stark", "wun-wun"], summary: "Jon Snow's forces, saved by Sansa's secret alliance with the Knights of the Vale, retake Winterfell and destroy House Bolton." },
  { id: "ev-s6-sept-explosion", season: 6, title: "Destruction of the Great Sept of Baelor", date: "Season 6", type: "death", houses: ["Lannister", "Tyrell"], characters: ["cersei-lannister", "margaery-tyrell", "loras-tyrell", "mace-tyrell", "high-sparrow"], summary: "Cersei detonates wildfire beneath the Great Sept, killing the High Sparrow, the Tyrells, and the Faith Militant leadership; she is crowned queen soon after." },
  { id: "ev-s6-kitn", season: 6, title: "Jon Snow proclaimed King in the North", date: "Season 6", type: "coronation", houses: ["Stark"], characters: ["jon-snow", "sansa-stark", "lyanna-mormont"], summary: "Northern lords, led by Lyanna Mormont, declare Jon Snow King in the North after retaking Winterfell." },

  { id: "ev-s7-loot-castamere", season: 7, title: "Daenerys attacks the Lannister supply train", date: "Season 7", type: "battle", houses: ["Targaryen", "Lannister"], characters: ["daenerys-targaryen", "jaime-lannister", "bronn"], summary: "Drogon and the Dothraki devastate a Lannister grain convoy at the Loot Train Battle." },
  { id: "ev-s7-dragonpit", season: 7, title: "The Dragonpit summit", date: "Season 7", type: "politics", houses: ["Stark", "Lannister", "Targaryen"], characters: ["jon-snow", "cersei-lannister", "daenerys-targaryen", "tyrion-lannister"], summary: "Westeros's rulers meet in King's Landing's ruined Dragonpit and agree to a truce against the army of the dead." },
  { id: "ev-s7-wall-falls", season: 7, title: "The Wall falls", date: "Season 7", type: "battle", houses: ["Targaryen", "Night's Watch"], characters: ["the-night-king", "viserion"], summary: "The Night King, riding a reanimated dragon, breaches the Wall at Eastwatch, opening the North to the army of the dead." },
  { id: "ev-s7-jon-dany", season: 7, title: "Jon and Daenerys become lovers", date: "Season 7", type: "other", houses: ["Stark", "Targaryen"], characters: ["jon-snow", "daenerys-targaryen"], summary: "Aboard ship to Winterfell, Jon and Daenerys begin a relationship, unaware they are aunt and nephew." },

  { id: "ev-s8-winterfell", season: 8, title: "Battle of Winterfell", date: "Season 8", type: "battle", houses: ["Stark", "Targaryen", "Free Folk", "Night's Watch"], characters: ["arya-stark", "the-night-king", "jon-snow", "theon-greyjoy", "lyanna-mormont", "jorah-mormont", "melisandre"], summary: "The living make their stand against the army of the dead; Arya Stark kills the Night King, ending the Long Night." },
  { id: "ev-s8-kingslanding", season: 8, title: "Battle of King's Landing", date: "Season 8", type: "battle", houses: ["Targaryen", "Lannister"], characters: ["daenerys-targaryen", "cersei-lannister", "jaime-lannister", "euron-greyjoy", "missandei"], summary: "Daenerys's fleet is devastated by Euron's scorpions and Missandei is executed; Daenerys later burns King's Landing to the ground despite the city's surrender." },
  { id: "ev-s8-cersei-jaime-death", season: 8, title: "Deaths of Cersei and Jaime Lannister", date: "Season 8", type: "death", houses: ["Lannister"], characters: ["cersei-lannister", "jaime-lannister"], summary: "The twins are crushed together beneath the collapsing Red Keep as King's Landing burns." },
  { id: "ev-s8-dany-death", season: 8, title: "Jon Snow kills Daenerys Targaryen", date: "Season 8", type: "death", houses: ["Targaryen", "Stark"], characters: ["jon-snow", "daenerys-targaryen", "drogon"], summary: "Jon stabs Daenerys to stop her tyranny after the burning of King's Landing; Drogon melts the Iron Throne in grief." },
  { id: "ev-s8-bran-king", season: 8, title: "Bran Stark elected King", date: "Season 8", type: "coronation", houses: ["Stark"], characters: ["bran-stark", "tyrion-lannister", "sansa-stark"], summary: "A council of lords, at Tyrion's urging, elects Bran the Broken as King of the Six Kingdoms; Sansa wins independence for the North." }
];

const SEASONS = [1, 2, 3, 4, 5, 6, 7, 8];
