// Shared quote dataset — feeds the Quote Wall and the "Who Said It" quiz.
const quotes = [
  { id: "q1", characterId: "ned-stark", text: "Winter is coming.", season: 1 },
  { id: "q2", characterId: "ned-stark", text: "The man who passes the sentence should swing the sword.", season: 1 },
  { id: "q3", characterId: "tyrion-lannister", text: "I drink and I know things.", season: 5 },
  { id: "q4", characterId: "tyrion-lannister", text: "Never forget what you are. The rest of the world will not. Wear it like armor and it can never be used to hurt you.", season: 1 },
  { id: "q5", characterId: "cersei-lannister", text: "When you play the game of thrones, you win or you die. There is no middle ground.", season: 1 },
  { id: "q6", characterId: "jon-snow", text: "I know nothing, Jon Snow.", season: 2 },
  { id: "q7", characterId: "daenerys-targaryen", text: "I am not going to stop the wheel. I'm going to break the wheel.", season: 5 },
  { id: "q8", characterId: "daenerys-targaryen", text: "Dracarys.", season: 3 },
  { id: "q9", characterId: "arya-stark", text: "A girl has no name.", season: 6 },
  { id: "q10", characterId: "arya-stark", text: "What do we say to the god of death? Not today.", season: 7 },
  { id: "q11", characterId: "arya-stark", text: "Valar Morghulis. Valar Dohaeris.", season: 4 },
  { id: "q12", characterId: "varys", text: "Power resides where men believe it resides. It's a trick, a shadow on the wall.", season: 2 },
  { id: "q13", characterId: "petyr-baelish", text: "Chaos isn't a pit. Chaos is a ladder.", season: 3 },
  { id: "q14", characterId: "sandor-clegane", text: "Anyone who tells you fighting is easy is talking about someone else's fight.", season: 1 },
  { id: "q15", characterId: "olenna-tyrell", text: "Tell Cersei. I want her to know it was me.", season: 7 },
  { id: "q16", characterId: "tywin-lannister", text: "A lion doesn't concern himself with the opinion of a sheep.", season: 4 },
  { id: "q17", characterId: "jaime-lannister", text: "The things I do for love.", season: 1 },
  { id: "q18", characterId: "hodor", text: "Hodor.", season: 1 },
  { id: "q19", characterId: "samwell-tarly", text: "I'm not going to be the maester who ran away from the battle. Not anymore.", season: 6 },
  { id: "q20", characterId: "brienne-of-tarth", text: "I don't want to marry a knight of the flowers or a knight of anything. I want to be a knight myself.", season: 4 },
  { id: "q21", characterId: "melisandre", text: "The night is dark and full of terrors.", season: 2 },
  { id: "q22", characterId: "bronn", text: "I like it when a girl fights back. Some girls fight back and just fight back and lose. I like the ones smart enough to know they can't win.", season: 1 },
  { id: "q23", characterId: "khal-drogo", text: "This one belongs to me. Moon of my life.", season: 1 },
  { id: "q24", characterId: "robb-stark", text: "The Lannisters are not the only ones who pay their debts.", season: 1 },
  { id: "q25", characterId: "davos-seaworth", text: "The Red Woman would have you believe there are two sides to this world, light and darkness. Watch your step. It's just a long drop to a cold, hard stone floor.", season: 5 },
  { id: "q26", characterId: "beric-dondarrion", text: "The Lord of Light has more use for a thief than a king.", season: 3 },
  { id: "q27", characterId: "jorah-mormont", text: "Whatever I am now, I was a knight once, and I learned the words when I was a boy. As a knight, I vow to protect the weak.", season: 1 },
  { id: "q28", characterId: "joffrey-baratheon", text: "Everyone is mine to torment.", season: 2 },
  { id: "q29", characterId: "ygritte", text: "You know nothing, Jon Snow.", season: 3 },
  { id: "q30", characterId: "pycelle", text: "Knowledge is a weapon, Jorah. Arm yourself well before you march into battle.", season: 2 },
  { id: "q31", characterId: "stannis-baratheon", text: "I will not question the Lord of Light's plans.", season: 3 },
  { id: "q32", characterId: "margaery-tyrell", text: "It's not easy being learned as well as beautiful.", season: 3 },
  { id: "q33", characterId: "gendry-baratheon", text: "I don't want to be a lord. I want to fight for Ned Stark's daughter.", season: 8 },
  { id: "q34", characterId: "missandei", text: "All men must die. But we are not men.", season: 6 },
  { id: "q35", characterId: "grey-worm", text: "There is only the fight.", season: 3 },
  { id: "q36", characterId: "oberyn-martell", text: "Everyone is mine to torment... said the wrong man. It's the Mountain who's mine.", season: 4 },
  { id: "q37", characterId: "tormund-giantsbane", text: "I'm gonna die at the wrong end of a pointy stick, cut down by some raggedy little farmer boy... in the muck, screaming for me mother.", season: 6 },
  { id: "q38", characterId: "sansa-stark", text: "I'm a slow learner, it's true, but I learn.", season: 7 },
  { id: "q39", characterId: "bran-stark", text: "I'm not really anyone anymore.", season: 7 },
  { id: "q40", characterId: "walder-frey", text: "The Freys and the Starks are friends again.", season: 3 },
  { id: "q41", characterId: "high-sparrow", text: "There is only one war that matters, the war between the living and the dead.", season: 6 },
  { id: "q42", characterId: "shae", text: "I'm yours and you're mine.", season: 1 },
  { id: "q43", characterId: "loras-tyrell", text: "The things we do for love.", season: 1 },
  { id: "q44", characterId: "robert-baratheon", text: "I was born to rule ten thousand years ago.", season: 1 }
];
