CREATE TABLE houses (
    name VARCHAR(100) PRIMARY KEY,
    words VARCHAR(250) NOT NULL,
    seat VARCHAR(250) NOT NULL,
    region VARCHAR(250) NOT NULL,
    sigil VARCHAR(100) NOT NULL,
    animal VARCHAR(150) NOT NULL,
    ruler_end VARCHAR(1000) NOT NULL,
    sigil_color VARCHAR(7) NOT NULL
);

CREATE TABLE relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(100) NOT NULL,
    target_id VARCHAR(100) NOT NULL,
    relationship_type VARCHAR(40) NOT NULL,
    subtype VARCHAR(40) NOT NULL,
    label VARCHAR(500) NOT NULL,
    CONSTRAINT fk_relationship_source FOREIGN KEY (source_id) REFERENCES character_records (id),
    CONSTRAINT fk_relationship_target FOREIGN KEY (target_id) REFERENCES character_records (id)
);
CREATE INDEX idx_relationships_source ON relationships (source_id);
CREATE INDEX idx_relationships_target ON relationships (target_id);
CREATE INDEX idx_relationships_type ON relationships (relationship_type);

CREATE TABLE episodes (
    id VARCHAR(20) PRIMARY KEY,
    season_number INTEGER NOT NULL,
    episode_number INTEGER NOT NULL,
    title VARCHAR(250) NOT NULL,
    air_date DATE NOT NULL,
    runtime_minutes INTEGER NOT NULL,
    director VARCHAR(250) NOT NULL,
    writers_json CLOB NOT NULL,
    summary CLOB NOT NULL,
    themes_json CLOB NOT NULL,
    character_ids_json CLOB NOT NULL,
    event_ids_json CLOB NOT NULL,
    CONSTRAINT episode_season_check CHECK (season_number BETWEEN 1 AND 8),
    CONSTRAINT episode_number_check CHECK (episode_number >= 1),
    CONSTRAINT episode_runtime_check CHECK (runtime_minutes > 0),
    CONSTRAINT uq_episode_season_number UNIQUE (season_number, episode_number)
);
CREATE INDEX idx_episodes_season ON episodes (season_number, episode_number);

CREATE TABLE quotes (
    id VARCHAR(20) PRIMARY KEY,
    character_id VARCHAR(100) NOT NULL,
    quote_text CLOB NOT NULL,
    season_number INTEGER NOT NULL,
    CONSTRAINT fk_quote_character FOREIGN KEY (character_id) REFERENCES character_records (id),
    CONSTRAINT quote_season_check CHECK (season_number BETWEEN 1 AND 8)
);
CREATE INDEX idx_quotes_character ON quotes (character_id);
CREATE INDEX idx_quotes_season ON quotes (season_number);

CREATE TABLE battles (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    season_number INTEGER NOT NULL,
    location VARCHAR(250) NOT NULL,
    combatants_json CLOB NOT NULL,
    outcome CLOB NOT NULL,
    casualties CLOB NOT NULL,
    linked_character_ids_json CLOB NOT NULL,
    linked_event_ids_json CLOB NOT NULL,
    CONSTRAINT battle_season_check CHECK (season_number BETWEEN 1 AND 8)
);
CREATE INDEX idx_battles_season ON battles (season_number);

CREATE TABLE story_events (
    id VARCHAR(100) PRIMARY KEY,
    season_number INTEGER NOT NULL,
    title VARCHAR(300) NOT NULL,
    event_date VARCHAR(100) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    houses_json CLOB NOT NULL,
    character_ids_json CLOB NOT NULL,
    summary CLOB NOT NULL,
    CONSTRAINT story_event_season_check CHECK (season_number BETWEEN 1 AND 8)
);
CREATE INDEX idx_story_events_season ON story_events (season_number);
CREATE INDEX idx_story_events_type ON story_events (event_type);
