import { useState } from "react";
import { getJson } from "../api";

const layers=[
  ["1","React frontend","Renders the interface, captures clicks and sends HTTP requests. It never reads the database directly."],
  ["2","Spring MVC controller","Receives `/api/v1` requests, validates parameters and translates HTTP into application calls."],
  ["3","Service layer","Coordinates business rules and transactions without knowing how the page looks."],
  ["4","JPA repository","Turns Java queries into SQL and maps database rows back into domain objects."],
  ["5","Flyway + H2","Flyway versions the schema. H2 stores durable rows in a local embedded database file."]
];
export default function ArchitecturePage(){const [endpoint,setEndpoint]=useState("/api/v1/statistics");const [result,setResult]=useState("");const [running,setRunning]=useState(false);async function send(){setRunning(true);setResult("");try{const data=await getJson<unknown>(endpoint);setResult(JSON.stringify(data,null,2))}catch(e){setResult(String(e))}finally{setRunning(false)}}return <main className="page"><div className="page-hero"><p className="eyebrow">INTERACTIVE SYSTEM GUIDE</p><h1>How the whole application works</h1><p>This page is built for learning together. Run a request, watch the live trace, and then connect each visible result to the layer that produced it.</p></div><section className="request-lab"><div><p className="eyebrow">TRY A REAL REQUEST</p><h2>API request laboratory</h2><p>Choose an endpoint. React will call Spring Boot, Spring Data will query H2, and the JSON response will appear here.</p><select aria-label="API endpoint" value={endpoint} onChange={e=>setEndpoint(e.target.value)}><option>/api/v1/statistics</option><option>/api/v1/characters?pageSize=3&amp;house=Stark</option><option>/api/v1/houses</option><option>/api/v1/episodes?pageSize=3&amp;season=1</option><option>/api/v1/battles?season=6</option><option>/api/v1/quotes?pageSize=3&amp;season=1</option></select><button onClick={send} disabled={running}>{running?"Request running…":"Send GET request"}</button></div><pre aria-live="polite">{result||"The JSON response will appear here."}</pre></section><section className="layer-list">{layers.map(([number,title,copy])=><article key={number}><span>{number}</span><div><h2>{title}</h2><p>{copy}</p></div></article>)}</section><section className="database-explainer"><div><p className="eyebrow">WHAT PERSISTS?</p><h2>Restart the backend. The data remains.</h2><p>The default JDBC URL uses H2 file mode. Flyway checks its schema-history table on every startup and applies only migrations that have not run before.</p></div><code>jdbc:h2:file:./data/game-of-thrones</code></section></main>}
